title: Mediterranean Atomic Tales
description: The Sunken Lands

plugins:
  - jekyll-theme-zendesk-garden

collections:
  bible:
    output: true
    permalink: /bible/:path/
  docs:
    output: true
    permalink: /docs/:path/

markdown: kramdown
