title: Mediterranean Atomic Tales
description: The Sunken Lands

remote_theme: zendesk/jekyll-theme-zendesk-garden

plugins:
  - jekyll-remote-theme

collections:
  bible:
    output: true
    permalink: /bible/:path/
  docs:
    output: true
    permalink: /docs/:path/

